version: "3.8"
services:
    frontendService:
        container_name: frontendService
        volumes:
            - ./ask_anything_frontend/:/app
        ports:
            - "443:443"
        image: node:slim
        command: bash -c "cd /app && npm install && npm run start"
        environment:
            - HTTPS=true
            - SSL_CRT_FILE=/app/cert.pem
            - SSL_KEY_FILE=/app/prvkey.pem
            - PORT=443
            - LINK=https://tungsnk.tech:8888
        networks:
            - network
    backendService:
        container_name: backendService
        volumes:
            - ./ask_anything_backend/:/app
        ports:
            - "8889:8889"
        image: node:slim
        command: bash -c "cd /app && npm install && npm run start"
        networks:
            - network
networks:
    network:
        driver: bridge